version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    ports:
      - "8082:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
